include:
  - project: "waldur/waldur-pipelines"
    file: "/templates/stages.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/test/check-merge-compatibility.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/release/sync-to-github.yml"

variables:
  GITHUB_OPENNODE_REPO_URL: "git@github.com:opennode/waldur-docs.git"
  GITHUB_WALDUR_REPO_URL: "git@github.com:waldur/waldur-docs.git"
