site_name: Waldur Documentation
theme:
  name: material
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
google_analytics:
  - UA-34543419-4
  - auto
plugins:
  - search
  - pdf-export
