site_name: Waldur Documentation
theme:
  name: material
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
google_analytics:
  - UA-34543419-4
  - auto
plugins:
  - search
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: true
      combined_output_path: pdf/waldur-docs.pdf
  - git-revision-date
copyright: Copyright &copy; 2016 - 2021 Waldur team
