site_name: Waldur Documentation
theme:
  name: material
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
google_analytics:
  - UA-34543419-4
  - auto
plugins:
  - search
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: true
  - git-revision-date
